### ISSUE TITLE
ft_memalloc()

### ISSUE THREAD

**Issue by Sacrimento** [Razshal/lem_in#1]
https://github.com/Razshal/lem_in/blob/8d84e0c13a069231326e35c8aeaf8bc6991194fe/src/lem_in.c#L20

La fonction ft_memalloc() de la libft permet de set à 0 toutes les valeurs des adresses allouées. Vous pourrez économiser un nombre considérable de ligne en utilisant cette dernière.

Sportivement,
abouvero

**Comment by Azelrack** [comment]
Oui bonjour merci d'avoir relevé ce problème je transmet votre suggestion à mon équipe et nous allons mettre en place un correctif ASAP.
Ameublement,
mfonteni
